export class EncuestaEmocionalEntidad {
  constructor(
    public readonly id: string | null,
    public readonly estudianteId: string,
    public readonly textoEmocional: string,
    public readonly nivelAnimo: number,
    public readonly nivelSeguridad: number,
    public readonly fechaCreacion: Date,
    public readonly puntajeRiesgo?: number,
    public readonly grado?: number,
    public readonly zonaJunin?: number,
    public readonly recreoSolo?: number,
    public readonly animoManana?: number,
    public readonly miedoParticipar?: number,
    public readonly redesSociales?: number,
    public readonly apoyoFamiliar?: number,
    public readonly rendimiento?: number,
    public readonly habilidadesSociales?: number,
    public readonly entornoViolento?: number,
    public readonly evaluacionIaDisponible?: boolean,
    public readonly nivelRiesgoIa?: string | null,
    public readonly prioridadAtencionIa?: string | null,
    public readonly analisisPsicologicoIa?: string | null,
    public readonly accionRecomendadaIa?: string | null,
    public readonly factoresDetectadosIa?: string[] | null,
    public readonly factoresProtectoresIa?: string[] | null,
    public readonly prediccionArbol?: number | null,
    public readonly sentimientoTextoIa?: string | null,
    public readonly confianzaTextoIa?: number | null,
    public readonly confianzaGlobalIa?: number | null,
  ) {}
}
